[env]
platform = espressif8266
board = esp8285
framework = arduino
lib_deps = 
    https://github.com/StuartsProjects/SX12XX-LoRa
monitor_speed = 115200

[env:master]
build_src_filter = +<master.cpp>

[env:slave]
build_src_filter = +<slave.cpp>

[env:native]
platform = native
test_framework = unity
test_build_src = true
build_src_filter = -<master.cpp> -<slave.cpp>
