[platformio]
default_envs = ground-node

[env]
test_framework = unity
test_build_src = true
lib_deps = 
    https://github.com/StuartsProjects/SX12XX-LoRa
    yoursunny/WifiEspNow @ ^0.0.20230713

[env:ground-node]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
test_filter = test_embedded
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<*> -<transponder.cpp> -<ground_radio.cpp> -<main.cpp>

[env:transponder]
platform = espressif8266
board = esp8285
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<ground_node.cpp> -<ground_radio.cpp> -<main.cpp>

[env:ground-radio]
platform = espressif8266
board = esp8285
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<ground_node.cpp> -<transponder.cpp> -<main.cpp>

[env:native]
platform = native
build_src_filter = -<*> +<logic.h> +<logic.cpp>
test_filter = test_native
