[platformio]
default_envs = ground-node

[env]
test_framework = unity
test_build_src = true

[env:ground-node]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<*> -<transponder.cpp> -<main.cpp>

[env:transponder]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<*> -<ground_node.cpp> -<main.cpp>

[env:native]
platform = native
build_src_filter = -<*> +<logic.h> +<logic.cpp>
